version = 1

# https://reuse.software

[[annotations]]
path = [
  "lacon-workspace/**",
  "tests/**",
  ".github/**",
  ".vscode/**",
  ".cargo/**",
  ".editorconfig",
  ".gitattributes",
  ".gitignore",

  ".rustfmt.toml",

  "Cargo.toml",
  "Cargo.lock",

  "README.md",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
  "SECURITY.md",
  "LICENSE",

  "Makefile.toml",
  "clippy.toml",
  "deny.toml",
  "rust-toolchain.toml",
  "REUSE.toml",

  "cspell.dic",
  "cspell.yml",
]
precedence = "override"
SPDX-FileCopyrightText = "LaCoN Developers"
SPDX-License-Identifier = "MIT"
