[toolchain]
channel = "1.89.0"
components = ["rustfmt", "clippy", "rust-analyzer"]
targets = [
  "wasm32-unknown-unknown",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  # "aarch64-apple-darwin",
  # "aarch64-unknown-linux-gnu",
]
profile = "minimal"
